using System.Net;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text.Encodings.Web;
using System.Text.Json;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.TestHost;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using LawnDart.Authorization;
using LawnDart.EventSourcing;
using LawnDart.EventStore;
using LawnDart.Projections.Lightweight.Tests.Helpers;
using LawnDart.Projections.Partitioning;
using LawnDart.Projections.Storage;

namespace LawnDart.Projections.Lightweight.Tests.Integration;

/// <summary>
/// In-process TestHost tests for the GET endpoints generated by <c>MapProjectionQueries()</c>.
/// </summary>
[Trait("Category", "Integration")]
public class MapProjectionQueriesTests : IAsyncLifetime
{
    private WebApplication? _app;
    private HttpClient? _client;

    private TestServer Server => _app!.GetTestServer();
    private HttpClient Client => _client!;

    public async Task InitializeAsync()
    {
        var builder = WebApplication.CreateBuilder();
        builder.WebHost.UseTestServer();
        builder.Logging.ClearProviders();

        builder.Services.AddLawnDart(o => { o.RequireTenantId = false; o.EnableAuthorization = false; });
        builder.Services.AddBoundedContext("default").UseInMemory();
        builder.Services.AddInMemoryProjectionStores();
        builder.Services.AddHttpContextAccessor();
        builder.Services.AddSingleton<IPartitioningService, SingleNodePartitioningService>();

        builder.Services.AddSingleton<IAuthorizationProvider, DefaultAuthorizationProvider>();
        builder.Services.AddSingleton<AuthorizationService>();

        builder.Services
            .AddAuthentication(TestScheme)
            .AddScheme<AuthenticationSchemeOptions, FakeAuthHandler>(TestScheme, _ => { });
        builder.Services.AddAuthorization();

        var registrations = new List<LawnDart.Projections.Lightweight.Registration.ProjectionRegistration>
        {
            new(
                handlerType: typeof(CounterSummaryProjection),
                viewType: typeof(CounterView),
                projectionName: "CounterSummary",
                kind: LawnDart.Projections.Lightweight.Registration.ProjectionKind.SingleStream,
                tenantScope: TenantScope.TenantScoped,
                streamType: "Counter",
                endpoint: new ProjectionEndpointAttribute(
                    route: "/api/views/counters/{counterId}",
                    requiredPermission: "Counter.View")),
            new(
                handlerType: typeof(GlobalTagIndexProjection),
                viewType: typeof(GlobalIndexView),
                projectionName: "GlobalTagIndex",
                kind: LawnDart.Projections.Lightweight.Registration.ProjectionKind.Global,
                tenantScope: TenantScope.SystemGlobal,
                endpoint: new ProjectionEndpointAttribute("/api/views/tags"))
        };

        builder.Services.AddSingleton<IReadOnlyList<LawnDart.Projections.Lightweight.Registration.ProjectionRegistration>>(registrations);

        _app = builder.Build();
        _app.UseAuthentication();
        _app.UseAuthorization();
        _app.MapProjectionQueries();

        await _app.StartAsync();
        _client = Server.CreateClient();
    }

    public async Task DisposeAsync()
    {
        _client?.Dispose();
        if (_app is not null)
            await _app.StopAsync();
    }

    private const string TestScheme = "FakeScheme";

    // ── Tests ──────────────────────────────────────────────────────────────────

    [Fact]
    public async Task TenantScoped_ValidJwt_WithView_Returns200()
    {
        const string tenantId = "tenant1";
        const string counterId = "abc123";
        const string instanceId = $"{tenantId}:Counter:{counterId}";

        var views = Server.Services.GetRequiredService<IViewStore>();
        await views.SaveViewAsync("CounterSummary:v1", instanceId,
            JsonSerializer.Serialize(new CounterView { Count = 42 }), 1);

        var request = BuildRequest($"/api/views/counters/{counterId}", tenantId, roles: ["Admin"]);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = await response.Content.ReadAsStringAsync();
        var view = JsonSerializer.Deserialize<CounterView>(body,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        Assert.Equal(42, view!.Count);
    }

    [Fact]
    public async Task TenantScoped_MissingTenantClaim_Returns401()
    {
        var request = BuildRequest("/api/views/counters/xyz", tenantId: null);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
    }

    [Fact]
    public async Task TenantScoped_MissingPermission_Returns403()
    {
        // "Student" role is not in DefaultAuthorizationProvider's map → no Counter.View permission
        var request = BuildRequest("/api/views/counters/xyz", tenantId: "acme", roles: ["Student"]);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.Forbidden, response.StatusCode);
    }

    [Fact]
    public async Task TenantScoped_ExplicitPermissionClaim_Returns200()
    {
        var views = Server.Services.GetRequiredService<IViewStore>();
        await views.SaveViewAsync("CounterSummary:v1", "acme:Counter:qqq",
            JsonSerializer.Serialize(new CounterView { Count = 7 }), 1);

        // User carries an explicit "permission" claim with value "Counter.View"
        var request = BuildRequest("/api/views/counters/qqq", tenantId: "acme",
            extraClaims: [new Claim("permission", "Counter.View")]);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task TenantScoped_AdminRole_Returns200()
    {
        var views = Server.Services.GetRequiredService<IViewStore>();
        await views.SaveViewAsync("CounterSummary:v1", "corp:Counter:rrr",
            JsonSerializer.Serialize(new CounterView { Count = 99 }), 1);

        var request = BuildRequest("/api/views/counters/rrr", tenantId: "corp", roles: ["Admin"]);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task TenantScoped_NoView_Returns404()
    {
        var request = BuildRequest("/api/views/counters/does-not-exist", tenantId: "foo", roles: ["Admin"]);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
    }

    [Fact]
    public async Task SystemGlobal_NoTenantClaimRequired_Returns200()
    {
        var views = Server.Services.GetRequiredService<IViewStore>();
        await views.SaveViewAsync("GlobalTagIndex:v1", "global",
            JsonSerializer.Serialize(new GlobalIndexView { TotalTags = 3 }), 1);

        // No tenant claim — SystemGlobal endpoint should not require one
        var request = BuildRequest("/api/views/tags", tenantId: null, roles: ["Admin"]);
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
    }

    [Fact]
    public async Task SystemGlobal_MultiNode_ResolvesNodeIsolatedInstanceId()
    {
        // Dedicated host: this node is partition 1 of 2 → GET must read global:n1, not "global".
        var builder = WebApplication.CreateBuilder();
        builder.WebHost.UseTestServer();
        builder.Logging.ClearProviders();

        builder.Services.AddLawnDart(o => { o.RequireTenantId = false; o.EnableAuthorization = false; });
        builder.Services.AddBoundedContext("default").UseInMemory();
        builder.Services.AddInMemoryProjectionStores();
        builder.Services.AddHttpContextAccessor();
        builder.Services.AddSingleton<IPartitioningService>(_ =>
            new ConsistentHashPartitioningService(1, 2));
        builder.Services.AddSingleton<IAuthorizationProvider, DefaultAuthorizationProvider>();
        builder.Services.AddSingleton<AuthorizationService>();
        builder.Services
            .AddAuthentication(TestScheme)
            .AddScheme<AuthenticationSchemeOptions, FakeAuthHandler>(TestScheme, _ => { });
        builder.Services.AddAuthorization();

        builder.Services.AddSingleton<IReadOnlyList<LawnDart.Projections.Lightweight.Registration.ProjectionRegistration>>(
        [
            new(
                handlerType: typeof(GlobalTagIndexProjection),
                viewType: typeof(GlobalIndexView),
                projectionName: "GlobalTagIndex",
                kind: LawnDart.Projections.Lightweight.Registration.ProjectionKind.Global,
                tenantScope: TenantScope.SystemGlobal,
                endpoint: new ProjectionEndpointAttribute("/api/views/tags"))
        ]);

        await using var app = builder.Build();
        app.UseAuthentication();
        app.UseAuthorization();
        app.MapProjectionQueries();
        await app.StartAsync();

        var views = app.Services.GetRequiredService<IViewStore>();
        await views.SaveViewAsync("GlobalTagIndex:v1", "global:n1",
            JsonSerializer.Serialize(new GlobalIndexView { TotalTags = 9 }), 2);
        await views.SaveViewAsync("GlobalTagIndex:v1", "global",
            JsonSerializer.Serialize(new GlobalIndexView { TotalTags = 1 }), 1);

        var client = app.GetTestServer().CreateClient();
        var request = BuildRequest("/api/views/tags", tenantId: null, roles: ["Admin"]);
        var response = await client.SendAsync(request);

        Assert.Equal(HttpStatusCode.OK, response.StatusCode);
        var body = await response.Content.ReadAsStringAsync();
        var view = JsonSerializer.Deserialize<GlobalIndexView>(body);
        Assert.Equal(9, view!.TotalTags);
    }

    [Fact]
    public async Task Unauthenticated_Request_Returns401()
    {
        var request = new HttpRequestMessage(HttpMethod.Get, "/api/views/tags");
        // No Authorization header
        var response = await Client.SendAsync(request);

        Assert.Equal(HttpStatusCode.Unauthorized, response.StatusCode);
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private static HttpRequestMessage BuildRequest(
        string path,
        string? tenantId,
        IEnumerable<string>? roles = null,
        IEnumerable<Claim>? extraClaims = null)
    {
        var request = new HttpRequestMessage(HttpMethod.Get, path);
        var header = BuildFakeBearerHeader(tenantId, roles, extraClaims);
        request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", header);
        return request;
    }

    private static string BuildFakeBearerHeader(
        string? tenantId,
        IEnumerable<string>? roles,
        IEnumerable<Claim>? extraClaims)
    {
        var pairs = new List<KeyValuePair<string, string>>();

        if (tenantId is not null)
            pairs.Add(new("tenant_id", tenantId));

        foreach (var role in roles ?? [])
            pairs.Add(new(ClaimTypes.Role, role));

        foreach (var claim in extraClaims ?? [])
            pairs.Add(new(claim.Type, claim.Value));

        var json = JsonSerializer.Serialize(pairs.Select(p => new { type = p.Key, value = p.Value }));
        return Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(json));
    }
}

// ── Fake authentication handler for tests ────────────────────────────────────

internal sealed class FakeAuthHandler : AuthenticationHandler<AuthenticationSchemeOptions>
{
    public FakeAuthHandler(
        IOptionsMonitor<AuthenticationSchemeOptions> options,
        ILoggerFactory logger,
        UrlEncoder encoder)
        : base(options, logger, encoder) { }

    protected override Task<AuthenticateResult> HandleAuthenticateAsync()
    {
        var header = Request.Headers.Authorization.ToString();

        if (string.IsNullOrEmpty(header) || !header.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
            return Task.FromResult(AuthenticateResult.NoResult());

        var token = header["Bearer ".Length..].Trim();

        try
        {
            var json = System.Text.Encoding.UTF8.GetString(Convert.FromBase64String(token));
            var claimsData = JsonSerializer.Deserialize<List<ClaimItem>>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true }) ?? [];

            var claims = claimsData
                .Select(c => new Claim(c.Type, c.Value))
                .Append(new Claim(ClaimTypes.Name, "test-user"))
                .ToList();

            var identity = new ClaimsIdentity(claims, Scheme.Name);
            var principal = new ClaimsPrincipal(identity);
            var ticket = new AuthenticationTicket(principal, Scheme.Name);

            return Task.FromResult(AuthenticateResult.Success(ticket));
        }
        catch
        {
            return Task.FromResult(AuthenticateResult.Fail("Invalid test token"));
        }
    }

    private record ClaimItem(string Type, string Value);
}
